--setVehicleHandling ( element theVehicle, string property, var value )

-- SaSi -- Utoljára frissítve 2019.05.20

--alapcuccos--
--setVehicleHandling(veh, "mass", 2600)
--setVehicleHandling(veh, "turnMass", 6333.3)
--setVehicleHandling(veh, "dragCoeff",2.0)
--setVehicleHandling(veh, "centerOfMass", { 0.0, 0.0, -0.2})
--setVehicleHandling(veh, "percentSubmerged", 80)
--setVehicleHandling(veh, "tractionMultiplier", 0.95)
--setVehicleHandling(veh, "tractionLoss", 0.70)
--setVehicleHandling(veh, "tractionBias", 0.46)
--setVehicleHandling(veh, "numberOfGears", 5)
--setVehicleHandling(veh, "maxVelocity", 860)  -- végsebesség 
--setVehicleHandling(veh, "engineAcceleration", 15)   -- Gyorsulás 
--setVehicleHandling(veh, "engineInertia", 30)
--setVehicleHandling(veh, "driveType", "FWD")
--setVehicleHandling(veh, "engineType", "petrol")
--setVehicleHandling(veh, "brakeDeceleration", 3.0)   -- fékezés 
--setVehicleHandling(veh, "brakeBias", 0.80)
--setVehicleHandling(veh, "ABS", false)
--setVehicleHandling(veh, "steeringLock", 44.0)
--setVehicleHandling(veh, "suspensionForceLevel", 1.5)
--setVehicleHandling(veh, "suspensionDamping", 0.07)
--setVehicleHandling(veh, "suspensionHighSpeedDamping", 2.0)
--setVehicleHandling(veh, "suspensionUpperLimit", 0.20)
--setVehicleHandling(veh, "suspensionLowerLimit", -0.12)
--setVehicleHandling(veh, "suspensionFrontRearBias", 0.45)
--setVehicleHandling(veh, "suspensionAntiDiveMultiplier", 0.0)
--setVehicleHandling(veh, "seatOffsetDistance", 0.2) 
--setVehicleHandling(veh, "collisionDamageMultiplier", 0.43)
--setVehicleHandling(veh, "monetary", 20000)
--setVehicleHandling(veh, "modelFlags", 1)
--setVehicleHandling(veh, "handlingFlags", 1)
--setVehicleHandling(veh, "headLight", 0)
--setVehicleHandling(veh, "tailLight", 3)
--setVehicleHandling(veh, "animGroup", 13)
--alapcuccos

--addEvent("UpdateHandling",true);

function loadHandling(v)	
		if getElementModel(v) == 551 then 									-- BMW i8
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 2500)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 0.9)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 6)
			setVehicleHandling(v, "maxVelocity", 160)
			setVehicleHandling(v, "engineAcceleration", 20)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 35)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.20)
		end
		if getElementModel(v) == 540 then 									-- BMW M5 E60
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 2500)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 0.9)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 6)
			setVehicleHandling(v, "maxVelocity", 190)
			setVehicleHandling(v, "engineAcceleration", 35)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 45)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.20)
		end
		if getElementModel(v) == 400 then 									-- Chevrolett Suburban Z11
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 2500)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 0.9)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 6)
			setVehicleHandling(v, "maxVelocity", 130)
			setVehicleHandling(v, "engineAcceleration", 30)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 35)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.10)
		end
		if getElementModel(v) == 496 then 									-- Dodge Ram 4X4
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 2500)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 0.9)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 6)
			setVehicleHandling(v, "maxVelocity", 140)
			setVehicleHandling(v, "engineAcceleration", 20)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 35)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.20)
		end
		if getElementModel(v) == 545 then 									-- Chrysler 1957
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 2500)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 0.9)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 6)
			setVehicleHandling(v, "maxVelocity", 140)
			setVehicleHandling(v, "engineAcceleration", 23)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "fwd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 35)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.20)
		end
		if getElementModel(v) == 475 then 									-- Plymouth Hemi Cuda
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 2500)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 0.9)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 6)
			setVehicleHandling(v, "maxVelocity", 170)
			setVehicleHandling(v, "engineAcceleration", 20)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 35)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.20)
		end
		if getElementModel(v) == 546 then 									-- Citroen C4 
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 2500)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 0.9)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 6)
			setVehicleHandling(v, "maxVelocity", 160)
			setVehicleHandling(v, "engineAcceleration", 14)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 35)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.20)
		end	
		if getElementModel(v) == 559 then 									-- Ferarri 458 italia 
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 2000)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 1.5)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 6)
			setVehicleHandling(v, "maxVelocity", 170)
			setVehicleHandling(v, "engineAcceleration", 50)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 35)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.10)
		end				
		if getElementModel(v) == 533 then 									-- Chrysler  Eldorado 
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 2000)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 1.2)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 6)
			setVehicleHandling(v, "maxVelocity", 140)
			setVehicleHandling(v, "engineAcceleration", 40)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "rwd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 35)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.10)
		end	
		if getElementModel(v) == 413 then 									-- Jeep 
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 2000)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 0.9)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 6)
			setVehicleHandling(v, "maxVelocity", 130)
			setVehicleHandling(v, "engineAcceleration", 10)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 35)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.10)
		end	
		if getElementModel(v) == 412 then 									-- Audi Sport Quattro 
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 2000)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 1.2)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 6)
			setVehicleHandling(v, "maxVelocity", 165)
			setVehicleHandling(v, "engineAcceleration", 60)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 60)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 50)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.10)	
		end
		if getElementModel(v) == 477 then 									-- Lamborghini Centenario 
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 3000)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 1.5)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 6)
			setVehicleHandling(v, "maxVelocity", 170)
			setVehicleHandling(v, "engineAcceleration", 45)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 40)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 30)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.0)
		end
		if getElementModel(v) == 585 then 									-- Mercedes-Benz C350
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 2500)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 0.9)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 6)
			setVehicleHandling(v, "maxVelocity", 160)
			setVehicleHandling(v, "engineAcceleration", 40)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 35)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.20)
		end
		if getElementModel(v) == 550 then 									-- BMW 760Li
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 3000)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 1.5)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 6)
			setVehicleHandling(v, "maxVelocity", 160)
			setVehicleHandling(v, "engineAcceleration", 45)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "rwd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 40)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 30)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.0)
		end
		if getElementModel(v) == 602 then 									-- Saleen Raptor
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 3000)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 1.3)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 6)
			setVehicleHandling(v, "maxVelocity", 170)
			setVehicleHandling(v, "engineAcceleration", 45)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 40)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 30)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.0)
		end
		if getElementModel(v) == 492 then 									-- Audi A6 3.0 
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 2500)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 0.9)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 6)
			setVehicleHandling(v, "maxVelocity", 170)
			setVehicleHandling(v, "engineAcceleration", 20)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 35)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.20)
		end
		if getElementModel(v) == 576 then 									-- Cougar Eliminator 
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 2000)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 0.9)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 6)
			setVehicleHandling(v, "maxVelocity", 155)
			setVehicleHandling(v, "engineAcceleration", 40)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "rwd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 30)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 35)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.10)
		end	
		if getElementModel(v) == 421 then                                     --Cadillac Escelade
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 2000)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 0.9)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 6)
			setVehicleHandling(v, "maxVelocity", 140)
			setVehicleHandling(v, "engineAcceleration", 40)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "rwd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 35)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.10)
			setVehicleHandling(v, "suspensionLowerLimit", -0.0)
		end	
		if getElementModel(v) == 436 then                                     --Cadillac Eldorado
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 2000)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 0.9)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 6)
			setVehicleHandling(v, "maxVelocity", 145)
			setVehicleHandling(v, "engineAcceleration", 40)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "rwd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 35)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.10)
			setVehicleHandling(v, "suspensionLowerLimit", -0.0)
		end	
		if getElementModel(v) == 418 then                                     --Cadillac Eldorado
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 2000)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 0.9)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 6)
			setVehicleHandling(v, "maxVelocity", 160)
			setVehicleHandling(v, "engineAcceleration", 40)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "rwd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 35)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.10)
			setVehicleHandling(v, "suspensionLowerLimit", -0.0)
		end	
		if getElementModel(v) == 491 then                                     --srt8
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 2000)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 1.5)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 6)
			setVehicleHandling(v, "maxVelocity", 180)
			setVehicleHandling(v, "engineAcceleration", 60)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 35)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.25)
		end	
		if getElementModel(v) == 411 then                                     --Saleen S7
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 2000)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 1.5)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 6)
			setVehicleHandling(v, "maxVelocity", 180)
			setVehicleHandling(v, "engineAcceleration", 80)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 20)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 35)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.10)
			setVehicleHandling(v, "suspensionLowerLimit", -0.0)
		end	
		if getElementModel(v) == 579 then                                     --Hummer H2
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 2000)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 0.9)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 6)
			setVehicleHandling(v, "maxVelocity", 150)
			setVehicleHandling(v, "engineAcceleration", 40)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 35)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.10)
		end	
		if getElementModel(v) == 587 then                                     --Land Rover RLX
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 2000)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 0.9)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 6)
			setVehicleHandling(v, "maxVelocity", 180)
			setVehicleHandling(v, "engineAcceleration", 80)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 80)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 35)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.10)
			setVehicleHandling(v, "suspensionLowerLimit", -0.0)
		end	
		if getElementModel(v) == 405 then                                     --Jaguar XF
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 2000)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 1.5)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 6)
			setVehicleHandling(v, "maxVelocity", 170)
			setVehicleHandling(v, "engineAcceleration", 80)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "rwd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 80)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 35)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.10)
		end	
		if getElementModel(v) == 439 then                                     --Nissan Skyline R32
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 2000)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 1.2)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 6)
			setVehicleHandling(v, "maxVelocity", 170)
			setVehicleHandling(v, "engineAcceleration", 40)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 35)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.14)
		end	
		if getElementModel(v) == 409 then                                     --Lincoln Town Car
			setVehicleHandling(v, "mass", 2000)
			setVehicleHandling(v, "turnMass", 2000)
			setVehicleHandling(v, "dragCoeff", 1.0)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 1.2)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 4)
			setVehicleHandling(v, "maxVelocity", 150)
			setVehicleHandling(v, "engineAcceleration", 40)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 35)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.0)
		end	
		if getElementModel(v) == 410 then                                     --Peugeot 206
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 2000)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 0.9)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 6)
			setVehicleHandling(v, "maxVelocity", 120)
			setVehicleHandling(v, "engineAcceleration", 40)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 35)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.10)
			setVehicleHandling(v, "suspensionLowerLimit", -0.0)
		end	
		if getElementModel(v) == 542 then                                     --Ford Pinto
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 2000)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 0.9)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 6)
			setVehicleHandling(v, "maxVelocity", 135)
			setVehicleHandling(v, "engineAcceleration", 40)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 35)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.10)
			setVehicleHandling(v, "suspensionLowerLimit", -0.0)
		end
		if getElementModel(v) == 445 then 									-- Mercedes Benz E500
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 2500)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 0.9)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 6)
			setVehicleHandling(v, "maxVelocity", 188)
			setVehicleHandling(v, "engineAcceleration", 40)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 35)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.20)
		end
		if getElementModel(v) == 562 then 									-- Nissan Skyline GT-R
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 2500)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 0.9)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 6)
			setVehicleHandling(v, "maxVelocity", 175)
			setVehicleHandling(v, "engineAcceleration", 35)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 35)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.20)
		end	
		if getElementModel(v) == 507 then 									-- Alfa Romeo Giulia
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 2500)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 0.9)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 6)
			setVehicleHandling(v, "maxVelocity", 160)
			setVehicleHandling(v, "engineAcceleration", 40)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 35)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.20)
		end	
		if getElementModel(v) == 527 then 									-- Bentley Continental SS 17
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 2500)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 1.5)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 6)
			setVehicleHandling(v, "maxVelocity", 165)
			setVehicleHandling(v, "engineAcceleration", 40)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 35)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.10)
		end
		if getElementModel(v) == 541 then 									-- Bugatti Chiron 2017
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 2500)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 1.7)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 6)
			setVehicleHandling(v, "maxVelocity", 200)
			setVehicleHandling(v, "engineAcceleration", 40)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 35)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.10)
		end	
		if getElementModel(v) == 506 then 									-- 2017 Porsche Boxster S
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 2500)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 0.9)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 6)
			setVehicleHandling(v, "maxVelocity", 195)
			setVehicleHandling(v, "engineAcceleration", 40)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 35)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.10)
		end	
		if getElementModel(v) == 451 then 									-- Ferrari F40
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 2500)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 0.9)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 6)
			setVehicleHandling(v, "maxVelocity", 199)
			setVehicleHandling(v, "engineAcceleration", 40)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 35)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.10)
		end	
		if getElementModel(v) == 560 then 									-- Subaru Impreza
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 2500)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 0.9)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 6)
			setVehicleHandling(v, "maxVelocity", 170)
			setVehicleHandling(v, "engineAcceleration", 40)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 35)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.20)
		end
				if getElementModel(v) == 558 then 									-- Nissan 350Z
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 2500)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 0.9)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 6)
			setVehicleHandling(v, "maxVelocity", 180)
			setVehicleHandling(v, "engineAcceleration", 20)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 35)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.20)
		end	
		if getElementModel(v) == 415 then 									-- Toyota Supra US-Spec 
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 2500)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 0.9)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 6)
			setVehicleHandling(v, "maxVelocity", 178)
			setVehicleHandling(v, "engineAcceleration", 40)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 35)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.10)
		end	
		if getElementModel(v) == 555 then 									-- 2016 Mercedes AMG
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 2500)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 0.9)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 6)
			setVehicleHandling(v, "maxVelocity", 199)
			setVehicleHandling(v, "engineAcceleration", 40)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 35)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.20)
		end	
		if getElementModel(v) == 429 then 									-- Laferrari
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 2500)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 0.9)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 6)
			setVehicleHandling(v, "maxVelocity", 205)
			setVehicleHandling(v, "engineAcceleration", 40)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 35)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.5)
			setVehicleHandling(v, "suspensionLowerLimit", -0.0)
		end	
		if getElementModel(v) == 529 then 									-- BMW M5 F10
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 2500)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 0.9)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 6)
			setVehicleHandling(v, "maxVelocity", 180)
			setVehicleHandling(v, "engineAcceleration", 35)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 45)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.10)
		end
		if getElementModel(v) == 566 then 									-- Mercedes Benz AMG GT63s 
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 2500)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 1.5)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 6)
			setVehicleHandling(v, "maxVelocity", 190)
			setVehicleHandling(v, "engineAcceleration", 35)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 45)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.12)
		end
		if getElementModel(v) == 534 then                                     --1969 Dodge Charger R/T
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 2500)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 0.9)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 6)
			setVehicleHandling(v, "maxVelocity", 185)
			setVehicleHandling(v, "engineAcceleration", 35)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 45)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.10)
		end
		if getElementModel(v) == 467 then 									-- Mercedes Benz 300 SEL
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 2500)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 0.9)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 6)
			setVehicleHandling(v, "maxVelocity", 175)
			setVehicleHandling(v, "engineAcceleration", 45)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 45)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.20)
		end
		if getElementModel(v) == 442 then 									-- Ford Mustang
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 2500)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 1.5)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 6)
			setVehicleHandling(v, "maxVelocity", 185)
			setVehicleHandling(v, "engineAcceleration", 50)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "rwd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 45)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.10)
		end
		if getElementModel(v) == 404 then 									-- Audi RS4
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 2500)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 1.5)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 6)
			setVehicleHandling(v, "maxVelocity", 180)
			setVehicleHandling(v, "engineAcceleration", 35)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "rwd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 45)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.20)
		end
		if getElementModel(v) == 401 then 									-- Hyundai HB20
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 2500)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 1.5)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 6)
			setVehicleHandling(v, "maxVelocity", 90)
			setVehicleHandling(v, "engineAcceleration", 35)
			setVehicleHandling(v, "engineInertia", 52)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 45)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.10)
		end
		if getElementModel(v) == 458 then 									-- Ford Focus RS
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 2500)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 1.5)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 6)
			setVehicleHandling(v, "maxVelocity", 200)
			setVehicleHandling(v, "engineAcceleration", 35)
			setVehicleHandling(v, "engineInertia", 52)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 45)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.10)
		end
		if getElementModel(v) == 419 then 									-- Audi R8 V10
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 2500)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 1.9)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 6)
			setVehicleHandling(v, "maxVelocity", 205)
			setVehicleHandling(v, "engineAcceleration", 30)
			setVehicleHandling(v, "engineInertia", 52)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 45)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.10)
		end
		if getElementModel(v) == 466 then 									-- benz gle450
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 2500)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 1.5)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 5)
			setVehicleHandling(v, "maxVelocity", 210)
			setVehicleHandling(v, "engineAcceleration", 30)
			setVehicleHandling(v, "engineInertia", 52)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 45)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.02)
			setVehicleHandling(v, "suspensionLowerLimit", -0.12)
		end
		if getElementModel(v) == 516 then 									-- Mercedes-Benz S500
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 2500)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 0.9)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 6)
			setVehicleHandling(v, "maxVelocity", 186)
			setVehicleHandling(v, "engineAcceleration", 35)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 45)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.20)
		end
		if getElementModel(v) == 502 then 									-- Nissan GTR R35
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 2500)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 1.5)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 6)
			setVehicleHandling(v, "maxVelocity", 180)
			setVehicleHandling(v, "engineAcceleration", 50)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 40)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.13)
		end
		if getElementModel(v) == 535 then 									-- Ford Mustang GT 2015
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 2500)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 1.5)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 6)
			setVehicleHandling(v, "maxVelocity", 200)
			setVehicleHandling(v, "engineAcceleration", 60)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 40)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.30)
		end			
-----------------------------------------FRAKCIO KOCSIK----------------------------------
		if getElementModel(v) == 416 then 									-- Ambulance
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 2500)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 1.5)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 6)
			setVehicleHandling(v, "maxVelocity", 170)
			setVehicleHandling(v, "engineAcceleration", 80)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 35)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.20)
		end
		if getElementModel(v) == 596 then 									-- Chevrolet Caprice Police(Police LS)
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 2500)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 1.5)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 6)
			setVehicleHandling(v, "maxVelocity", 180)
			setVehicleHandling(v, "engineAcceleration", 40)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 35)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.20)
		end	
		if getElementModel(v) == 598 then 									-- Dodge Charger(Police LV)
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 2500)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 1.5)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 6)
			setVehicleHandling(v, "maxVelocity", 190)
			setVehicleHandling(v, "engineAcceleration", 40)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 35)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.20)
		end	
		if getElementModel(v) == 597 then 									-- Ford EXP(Police SF)
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 2500)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 1.5)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 6)
			setVehicleHandling(v, "maxVelocity", 300)
			setVehicleHandling(v, "engineAcceleration", 40)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 35)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.20)
		end	
		if getElementModel(v) == 599 then                                     --Ford F150
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 2500)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 1.5)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 6)
			setVehicleHandling(v, "maxVelocity", 190)
			setVehicleHandling(v, "engineAcceleration", 60)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 35)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.10)
		end
		---if getElementModel(v) == 525 then                                     --Towtruck
			---setVehicleHandling(v, "mass", 1600)
			--setVehicleHandling(v, "turnMass", 2000)
			--setVehicleHandling(v, "dragCoeff", 1.8)
			--setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			--setVehicleHandling(v, "percentSubmerged", 75)
			--setVehicleHandling(v, "tractionMultiplier", 0.9)
			--setVehicleHandling(v, "tractionLoss", 0.9)
			--setVehicleHandling(v, "tractionBias", 0.497)
			--setVehicleHandling(v, "numberOfGears", 6)
			--setVehicleHandling(v, "maxVelocity", 155)
			--setVehicleHandling(v, "engineAcceleration", 40)
			--setVehicleHandling(v, "engineInertia", 50)
			--setVehicleHandling(v, "driveType", "awd")
			--setVehicleHandling(v, "engineType", "petrol")
			--setVehicleHandling(v, "brakeDeceleration", 50)
			--setVehicleHandling(v, "ABS", false)
			--setVehicleHandling(v, "steeringLock", 35)
			--setVehicleHandling(v, "headLight", 0)
			---setVehicleHandling(v, "tailLight", 1)
			----setVehicleHandling(v, "animGroup", 0)
--			setVehicleHandling(v, "suspensionUpperLimit", 0.10)
			--setVehicleHandling(v, "suspensionLowerLimit", -0.0)
		--end	
		if getElementModel(v) == 420 then                                     --Taxi
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 2000)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 0.9)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 6)
			setVehicleHandling(v, "maxVelocity", 140)
			setVehicleHandling(v, "engineAcceleration", 40)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 35)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.10)
		end	
		if getElementModel(v) == 438 then                                     --Cabbie
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 2000)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 0.9)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 6)
			setVehicleHandling(v, "maxVelocity", 155)
			setVehicleHandling(v, "engineAcceleration", 40)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 35)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.10)
		end	
		if getElementModel(v) == 490 then                                     --Police casual
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 2500)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 0.9)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 6)
			setVehicleHandling(v, "maxVelocity", 190)
			setVehicleHandling(v, "engineAcceleration", 60)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 35)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.10)
		end	
		if getElementModel(v) == 528 then                                     --FBI Truck
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 2500)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 0.9)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 6)
			setVehicleHandling(v, "maxVelocity", 180)
			setVehicleHandling(v, "engineAcceleration", 60)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 35)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.10)
		end	
		if getElementModel(v) == 427 then                                     --SWAT ENFORCER
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 2500)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 1.5)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 6)
			setVehicleHandling(v, "maxVelocity", 145)
			setVehicleHandling(v, "engineAcceleration", 60)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 40)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.10)
		end
		if getElementModel(v) == 428 then                                     --SWAT HEAVY
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 2500)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 0.9)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 6)
			setVehicleHandling(v, "maxVelocity", 155)
			setVehicleHandling(v, "engineAcceleration", 60)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 55)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.10)
		end	
--------------------------------------MOTOROK----------------------------------------------
		if getElementModel(v) == 522 then                                     --Honda Falcon
				setVehicleHandling(v, "maxVelocity", 100)
				setVehicleHandling(v, "engineAcceleration", 40.0)
				setVehicleHandling(v, "engineInertia", 5.0)
				setVehicleHandling(v, "engineType", "petrol")
				setVehicleHandling(v, "driveType", "awd")
				setVehicleHandling(v, "steeringLock", 35.0)
				setVehicleHandling(v, "tractionMultiplier", 1.8)
                setVehicleHandling(v, "tractionLoss", 1.15)
                setVehicleHandling(v, "tractionBias", 0.5)
				setVehicleHandling(v, "brakeDeceleration", 10.0)
				setVehicleHandling(v, "centerOfMass", { 0.0, 0.0, -0.09})
				setVehicleHandling(v, "dragCoeff",0.0)
		end
		if getElementModel(v) == 586 then                                     --Honda BeAT
				setVehicleHandling(v, "maxVelocity", 100)
				setVehicleHandling(v, "engineAcceleration", 50.0)
				setVehicleHandling(v, "engineInertia", 5.0)
				setVehicleHandling(v, "engineType", "petrol")
				setVehicleHandling(v, "driveType", "awd")
				setVehicleHandling(v, "steeringLock", 35.0)
				setVehicleHandling(v, "tractionMultiplier", 1.8)
                setVehicleHandling(v, "tractionLoss", 1.15)
                setVehicleHandling(v, "tractionBias", 0.5)
				setVehicleHandling(v, "brakeDeceleration", 10.0)
				setVehicleHandling(v, "centerOfMass", { 0.0, 0.0, -0.09})
				setVehicleHandling(v, "dragCoeff",0.0)
		end
		if getElementModel(v) == 468 then                                     --BF-400
				setVehicleHandling(v, "maxVelocity", 250)
				setVehicleHandling(v, "engineAcceleration", 40.0)
				setVehicleHandling(v, "engineInertia", 5.0)
				setVehicleHandling(v, "engineType", "petrol")
				setVehicleHandling(v, "driveType", "awd")
				setVehicleHandling(v, "steeringLock", 35.0)
				setVehicleHandling(v, "tractionMultiplier", 1.8)
                setVehicleHandling(v, "tractionLoss", 1.15)
                setVehicleHandling(v, "tractionBias", 0.5)
				setVehicleHandling(v, "brakeDeceleration", 10.0)
				setVehicleHandling(v, "centerOfMass", { 0.0, 0.0, -0.09})
				setVehicleHandling(v, "dragCoeff",0.0)
		end
----------------------------------EGYEDI KOCSIK---------------------------------------------
		if getElementModel(v) == 494 then 									-- NemtomxDcsak kértétek
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 2500)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 0.9)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 6)
			setVehicleHandling(v, "maxVelocity", 243)
			setVehicleHandling(v, "engineAcceleration", 40)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 35)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.10)
		end	
		if getElementModel(v) == 549 then 									-- RUF RT12S
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 2500)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 1.5)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 6)
			setVehicleHandling(v, "maxVelocity", 230)
			setVehicleHandling(v, "engineAcceleration", 40)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 35)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.10)
		end	
		if getElementModel(v) == 517 then 									-- MCLaren P1
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 2500)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 1.5)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 6)
			setVehicleHandling(v, "maxVelocity", 290)
			setVehicleHandling(v, "engineAcceleration", 45)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 35)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.10)
		end	
		if getElementModel(v) == 603 then 									-- Hennessey Venom
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 2500)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 1.5)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 6)
			setVehicleHandling(v, "maxVelocity", 255)
			setVehicleHandling(v, "engineAcceleration", 40)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 35)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.10)
		end	
		if getElementModel(v) == 474 then 									-- BMW M3 E30
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 2000)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 1.5)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 6)
			setVehicleHandling(v, "maxVelocity", 230)
			setVehicleHandling(v, "engineAcceleration", 30)
			setVehicleHandling(v, "engineInertia", 25)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 30)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 30)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.10)	
		end
		if getElementModel(v) == 561 then 									-- PP BMW m5 F90
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 2500)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 1.5)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 6)
			setVehicleHandling(v, "maxVelocity", 250)
			setVehicleHandling(v, "engineAcceleration", 40)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 35)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.10)
		end
		if getElementModel(v) == 402 then 									-- PP BMW m1
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 2500)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 1.2)
			setVehicleHandling(v, "tractionLoss", 1.5)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 6)
			setVehicleHandling(v, "maxVelocity", 266)
			setVehicleHandling(v, "engineAcceleration", 40)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 35)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.10)
		end
				if getElementModel(v) == 600 then 									-- PP 2019 Bugatti
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 4000)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 2.5)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 6)
			setVehicleHandling(v, "maxVelocity", 290)
			setVehicleHandling(v, "engineAcceleration", 40)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 35)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.10)
		end
		if getElementModel(v) == 518 then 									-- Lykan Hypersport
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 2500)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 2.8)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 6)
			setVehicleHandling(v, "maxVelocity", 240)
			setVehicleHandling(v, "engineAcceleration", 80)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 35)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.10)
		end	
		if getElementModel(v) == 565 then 									-- MCLaren Senna 2019
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 2500)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 1.5)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 6)
			setVehicleHandling(v, "maxVelocity", 265)
			setVehicleHandling(v, "engineAcceleration", 45)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 35)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.10)
		end	
		if getElementModel(v) == 526 then 									-- Lambo Huracan Liberty
			setVehicleHandling(v, "mass", 3000)
			setVehicleHandling(v, "turnMass", 2500)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 2.8)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 6)
			setVehicleHandling(v, "maxVelocity", 270)
			setVehicleHandling(v, "engineAcceleration", 60)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 35)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.10)
		end
		if getElementModel(v) == 547 then 									-- Brabus Rocket 900
			setVehicleHandling(v, "mass", 3000)
			setVehicleHandling(v, "turnMass", 2500)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 2.2)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.450)
			setVehicleHandling(v, "numberOfGears", 6)
			setVehicleHandling(v, "maxVelocity", 260)
			setVehicleHandling(v, "engineAcceleration", 55)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 60)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 25)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.12)
		end
		if getElementModel(v) == 580 then 									-- Audi RS7
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 2500)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.4 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 1.8)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 6)
			setVehicleHandling(v, "maxVelocity", 283)
			setVehicleHandling(v, "engineAcceleration", 70)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 35)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.05)
		end
		if getElementModel(v) == 589 then 									-- Camaro ZL1
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 2500)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 1.5)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 7)
			setVehicleHandling(v, "maxVelocity", 280)
			setVehicleHandling(v, "engineAcceleration", 50)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 35)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.10)
		end
		if getElementModel(v) == 605 then 									-- Lambo Veneno
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 2500)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 1.9)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.497)
			setVehicleHandling(v, "numberOfGears", 6)
			setVehicleHandling(v, "maxVelocity", 260)
			setVehicleHandling(v, "engineAcceleration", 55)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 35)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.10)
		end
		if getElementModel(v) == 554 then 									-- ferrari 488 pista
			setVehicleHandling(v, "mass", 1600)
			setVehicleHandling(v, "turnMass", 2500)
			setVehicleHandling(v, "dragCoeff", 1.8)
			setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
			setVehicleHandling(v, "percentSubmerged", 75)
			setVehicleHandling(v, "tractionMultiplier", 1.9)
			setVehicleHandling(v, "tractionLoss", 0.9)
			setVehicleHandling(v, "tractionBias", 0.400)
			setVehicleHandling(v, "numberOfGears", 6)
			setVehicleHandling(v, "maxVelocity", 260)
			setVehicleHandling(v, "engineAcceleration", 60)
			setVehicleHandling(v, "engineInertia", 50)
			setVehicleHandling(v, "driveType", "awd")
			setVehicleHandling(v, "engineType", "petrol")
			setVehicleHandling(v, "brakeDeceleration", 50)
			setVehicleHandling(v, "ABS", false)
			setVehicleHandling(v, "steeringLock", 35)
			setVehicleHandling(v, "headLight", 0)
			setVehicleHandling(v, "tailLight", 1)
			setVehicleHandling(v, "animGroup", 0)
			setVehicleHandling(v, "suspensionUpperLimit", 0.0)
			setVehicleHandling(v, "suspensionLowerLimit", -0.13)
		end
		
	--end	
end
function loadHandlings()
    for k, v in ipairs(getElementsByType("vehicle")) do
        loadHandling(v)
    end
end
addEventHandler("onResourceStart", getResourceRootElement(getThisResource()), loadHandlings)

 
-- function resetHandling()
    -- for k, v in ipairs(getElementsByType("vehicle")) do
        -- for k1,v1 in ipairs(setModelHandling(getVehicleModel(v))) do
            -- setVehicleHandling(v, k1, nil)
        -- end
    -- end
-- end
-- addEventHandler("onResourceStop", getResourceRootElement(getThisResource()), resetHandling)

function loadHandlingToVehicle()
    loadHandling(source)
end
addEventHandler("onVehicleEnter", root, loadHandlingToVehicle)