txd = engineLoadTXD ( "bennys.txd" )
engineImportTXD ( txd, 5310 )
col = engineLoadCOL ( "bext.col" )
engineReplaceCOL ( col, 5310 )
dff = engineLoadDFF ( "bext.dff", 0 )
engineReplaceModel ( dff, 5310 )
engineSetModelLODDistance(5310, 170)

txd = engineLoadTXD ( "bennys.txd" )
engineImportTXD ( txd, 1915 )
col = engineLoadCOL ( "bprops.col" )
engineReplaceCOL ( col, 1915 )
dff = engineLoadDFF ( "bprops.dff", 0 )
engineReplaceModel ( dff, 1915 )
engineSetModelLODDistance(1915, 170)

txd = engineLoadTXD ( "bennys.txd" )
engineImportTXD ( txd, 1905 )
col = engineLoadCOL ( "bshell.col" )
engineReplaceCOL ( col, 1905 )
dff = engineLoadDFF ( "bshell.dff", 0 )
engineReplaceModel ( dff, 1905 )
engineSetModelLODDistance(1905, 170)

txd = engineLoadTXD ( "bennys.txd" )
engineImportTXD ( txd, 1906 )
col = engineLoadCOL ( "bprt2.col" )
engineReplaceCOL ( col, 1906 )
dff = engineLoadDFF ( "bprt2.dff", 0 )
engineReplaceModel ( dff, 1906 )
engineSetModelLODDistance(1906, 170)

txd = engineLoadTXD ( "bennys.txd" )
engineImportTXD ( txd, 1910 )
col = engineLoadCOL ( "bshit.col" )
engineReplaceCOL ( col, 1910 )
dff = engineLoadDFF ( "bshit.dff", 0 )
engineReplaceModel ( dff, 1910 )
engineSetModelLODDistance(1910, 170)

txd = engineLoadTXD ( "bennys.txd" )
engineImportTXD ( txd, 1862 )
col = engineLoadCOL ( "bvehic.col" )
engineReplaceCOL ( col, 1862 )
dff = engineLoadDFF ( "bvehic.dff", 0 )
engineReplaceModel ( dff, 1862 )
engineSetModelLODDistance(1862, 170)

txd = engineLoadTXD ( "bennys2.txd" )
engineImportTXD ( txd, 1863 )
col = engineLoadCOL ( "framewov.col" )
engineReplaceCOL ( col, 1863 )
dff = engineLoadDFF ( "framewov.dff", 0 )
engineReplaceModel ( dff, 1863 )
engineSetModelLODDistance(1863, 170)

txd = engineLoadTXD ( "bennys.txd" )
engineImportTXD ( txd, 1864 )
col = engineLoadCOL ( "lamps_von.col" )
engineReplaceCOL ( col, 1864 )
dff = engineLoadDFF ( "lamps_von.dff", 0 )
engineReplaceModel ( dff, 1864 )
engineSetModelLODDistance(1864, 170)

txd = engineLoadTXD ( "bennys2.txd" )
engineImportTXD ( txd, 1865 )
col = engineLoadCOL ( "llframe.col" )
engineReplaceCOL ( col, 1865 )
dff = engineLoadDFF ( "llframe.dff", 0 )
engineReplaceModel ( dff, 1865 )
engineSetModelLODDistance(1865, 170)

txd = engineLoadTXD ( "bennys.txd" )
engineImportTXD ( txd, 1866 )
col = engineLoadCOL ( "lr_banners1.col" )
engineReplaceCOL ( col, 1866 )
dff = engineLoadDFF ( "lr_banners1.dff", 0 )
engineReplaceModel ( dff, 1866 )
engineSetModelLODDistance(1866, 170)

txd = engineLoadTXD ( "bennys.txd" )
engineImportTXD ( txd, 1867 )
col = engineLoadCOL ( "lr_banners2.col" )
engineReplaceCOL ( col, 1867 )
dff = engineLoadDFF ( "lr_banners2.dff", 0 )
engineReplaceModel ( dff, 1867 )
engineSetModelLODDistance(1867, 170)

txd = engineLoadTXD ( "bennys.txd" )
engineImportTXD ( txd, 1868 )
col = engineLoadCOL ( "lr_banners3.col" )
engineReplaceCOL ( col, 1868 )
dff = engineLoadDFF ( "lr_banners3.dff", 0 )
engineReplaceModel ( dff, 1868 )
engineSetModelLODDistance(1868, 170)

txd = engineLoadTXD ( "bennys.txd" )
engineImportTXD ( txd, 1869 )
col = engineLoadCOL ( "lr_banners4.col" )
engineReplaceCOL ( col, 1869 )
dff = engineLoadDFF ( "lr_banners4.dff", 0 )
engineReplaceModel ( dff, 1869 )
engineSetModelLODDistance(1869, 170)

txd = engineLoadTXD ( "bennys.txd" )
engineImportTXD ( txd, 1870 )
col = engineLoadCOL ( "lr_carlift.col" )
engineReplaceCOL ( col, 1870 )
dff = engineLoadDFF ( "lr_carlift.dff", 0 )
engineReplaceModel ( dff, 1870 )
engineSetModelLODDistance(1870, 170)

txd = engineLoadTXD ( "bennys.txd" )
engineImportTXD ( txd, 1872 )
col = engineLoadCOL ( "lr_grafitib.col" )
engineReplaceCOL ( col, 1872 )
dff = engineLoadDFF ( "lr_grafitib.dff", 0 )
engineReplaceModel ( dff, 1872 )
engineSetModelLODDistance(1872, 170)

txd = engineLoadTXD ( "bennys.txd" )
engineImportTXD ( txd, 1873 )
col = engineLoadCOL ( "lr_grafside.col" )
engineReplaceCOL ( col, 1873 )
dff = engineLoadDFF ( "lr_grafside.dff", 0 )
engineReplaceModel ( dff, 1873 )
engineSetModelLODDistance(1873, 170)

txd = engineLoadTXD ( "bennys.txd" )
engineImportTXD ( txd, 1874 )
col = engineLoadCOL ( "lr_mezzanin.col" )
engineReplaceCOL ( col, 1874 )
dff = engineLoadDFF ( "lr_mezzanin.dff", 0 )
engineReplaceModel ( dff, 1874 )
engineSetModelLODDistance(1874, 170)

txd = engineLoadTXD ( "bennys.txd" )
engineImportTXD ( txd, 1875 )
col = engineLoadCOL ( "lr_montageb.col" )
engineReplaceCOL ( col, 1875 )
dff = engineLoadDFF ( "lr_montageb.dff", 0 )
engineReplaceModel ( dff, 1875 )
engineSetModelLODDistance(1875, 170)

txd = engineLoadTXD ( "bennys.txd" )
engineImportTXD ( txd, 1876 )
col = engineLoadCOL ( "lr_montx.col" )
engineReplaceCOL ( col, 1876 )
dff = engineLoadDFF ( "lr_montx.dff", 0 )
engineReplaceModel ( dff, 1876 )
engineSetModelLODDistance(1876, 170)

txd = engineLoadTXD ( "bennys.txd" )
engineImportTXD ( txd, 1877 )
col = engineLoadCOL ( "lr_pillars.col" )
engineReplaceCOL ( col, 1877 )
dff = engineLoadDFF ( "lr_pillars.dff", 0 )
engineReplaceModel ( dff, 1877 )
engineSetModelLODDistance(1877, 170)

txd = engineLoadTXD ( "bennys.txd" )
engineImportTXD ( txd, 1878 )
col = engineLoadCOL ( "lr_racksb.col" )
engineReplaceCOL ( col, 1878 )
dff = engineLoadDFF ( "lr_racksb.dff", 0 )
engineReplaceModel ( dff, 1878 )
engineSetModelLODDistance(1878, 170)

txd = engineLoadTXD ( "bennys.txd" )
engineImportTXD ( txd, 1879 )
col = engineLoadCOL ( "lr_rail1.col" )
engineReplaceCOL ( col, 1879 )
dff = engineLoadDFF ( "lr_rail1.dff", 0 )
engineReplaceModel ( dff, 1879 )
engineSetModelLODDistance(1879, 170)

txd = engineLoadTXD ( "bennys.txd" )
engineImportTXD ( txd, 1880 )
col = engineLoadCOL ( "lr_rail2.col" )
engineReplaceCOL ( col, 1880 )
dff = engineLoadDFF ( "lr_rail2.dff", 0 )
engineReplaceModel ( dff, 1880 )
engineSetModelLODDistance(1880, 170)

txd = engineLoadTXD ( "bennys.txd" )
engineImportTXD ( txd, 1881 )
col = engineLoadCOL ( "lr_ramps.col" )
engineReplaceCOL ( col, 1881 )
dff = engineLoadDFF ( "lr_ramps.dff", 0 )
engineReplaceModel ( dff, 1881 )
engineSetModelLODDistance(1881, 170)

txd = engineLoadTXD ( "bennys.txd" )
engineImportTXD ( txd, 1882 )
col = engineLoadCOL ( "lr_spray.col" )
engineReplaceCOL ( col, 1882 )
dff = engineLoadDFF ( "lr_spray.dff", 0 )
engineReplaceModel ( dff, 1882 )
engineSetModelLODDistance(1882, 170)

txd = engineLoadTXD ( "bennys.txd" )
engineImportTXD ( txd, 1902 )
col = engineLoadCOL ( "v_doorbenny.col" )
engineReplaceCOL ( col, 1902 )
dff = engineLoadDFF ( "v_doorbenny.dff", 0 )
engineReplaceModel ( dff, 1902 )
engineSetModelLODDistance(1902, 170)

txd = engineLoadTXD ( "bennys.txd" )
engineImportTXD ( txd, 1903 )
col = engineLoadCOL ( "lr_office.col" )
engineReplaceCOL ( col, 1903 )
dff = engineLoadDFF ( "lr_office.dff", 0 )
engineReplaceModel ( dff, 1903 )
engineSetModelLODDistance(1903, 170)

txd = engineLoadTXD ( "bennys.txd" )
engineImportTXD ( txd, 1904 )
col = engineLoadCOL ( "lr_ramps_s.col" )
engineReplaceCOL ( col, 1904 )
dff = engineLoadDFF ( "lr_ramps_s.dff", 0 )
engineReplaceModel ( dff, 1904 )
engineSetModelLODDistance(1904, 170)

-- Onde estiver ID, coloque o ID do objeto que você quer substituir.
-- Onde estiver NOME, você coloca o nome dos arquivos na pasta "Skins".
-- No engineSetModelLODDistance você coloca a ID do objeto, logo em seguida a distância que você quer que ele renderize, o máximo permitido pelo MTA é 170.